# Generated by Django 4.1.13 on 2024-01-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_image',
            field=models.ImageField(default='default_image.jpg', upload_to='receipe/'),
        ),
    ]
